continents:
  MASTER:
    MASTER:
      mirrors:
        - name: "Master"
          url: "https://deb.parrot.sh/mirrors/parrot"
          index: index.db.iso
          version: 9999
          down: false
  DEFAULT:
    DEFAULT:
      mirrors:
        #- name: 'cdn.bunny'
        #  url: 'https://bunny.deb.parrot.sh/parrot'
        #  index: index.db.iso
        - name: 'edge1.legolas'
          url: 'https://legolas.edge1.parrot.run/parrot'
          index: index.db.iso
        - name: 'edge1.gimli'
          url: 'https://gimli.edge1.parrot.run/parrot'
          index: index.db.iso
        - name: 'edge1.meriadoc'
          url: 'https://meriadoc.edge1.parrot.run/parrot'
          index: index.db.iso
        - name: 'edge1.peregrino'
          url: 'https://peregrino.edge1.parrot.run/parrot'
          index: index.db.iso
        - name: 'edge1.gandalf'
          url: 'https://gandalf.edge1.parrot.run/parrot'
          index: index.db.iso
        - name: 'edge1.saruman'
          url: 'https://saruman.edge1.parrot.run/parrot'
          index: index.db.iso
