continents:
  MASTER:
    MASTER:
      mirrors:
        - name: "Master"
          url: "https://deb.parrot.sh/parrot"
          index: vindex.iso.db
          version: 9999
          down: false
  DEFAULT:
    DEFAULT:
      mirrors:
        - name: 'bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: vindex.iso.db
        - name: 'apac.alibaba'
          url: 'https://mirrors.aliyun.com/parrot/'
          index: vindex.iso.db

  EU:
    DEFAULT:
      mirrors:
        - name: 'bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: vindex.iso.db

  AF:
    DEFAULT:
      mirrors:
        - name: 'bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: vindex.iso.db
  NA:
    DEFAULT:
      mirrors:
        - name: 'bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: vindex.iso.db
  SA:
    DEFAULT:
      mirrors:
        - name: 'bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: vindex.iso.db
  AS:
    DEFAULT:
      mirrors:
        - name: 'bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: vindex.iso.db
  OC:
    DEFAULT:
      mirrors:
        - name: 'bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: vindex.iso.db
        
