continents:
  MASTER:
    MASTER:
      mirrors:
        - name: "Master"
          url: "https://deb.parrot.sh/mirrors/parrot"
          index: index.db.iso
          version: 9999
          down: false
  DEFAULT:
    DEFAULT:
      mirrors:
        #- name: 'cdn.bunny'
        #  url: 'https://bunny.deb.parrot.sh/parrot'
        #  index: index.db.iso
        - name: 'edge1'
          url: 'https://edge1.parrot.run/parrot'
          index: index.db.iso
        #- name: 'edge2'
        #  url: 'https://edge2.parrot.run/parrot'
        #  index: index.db.iso
        #- name: 'edge3'
        #  url: 'https://edge3.parrot.run/parrot'
        #  index: index.db.iso
