continents:
  MASTER:
    MASTER:
      mirrors:
        - name: "Master"
          url: "https://deb.parrot.sh/mirrors/parrot"
          index: index.db.iso
          version: 9999
          down: false
  DEFAULT:
    DEFAULT:
      mirrors:
        #- name: 'cdn.bunny'
        #  url: 'https://bunny.deb.parrot.sh/parrot'
        #  index: index.db.iso
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db.iso
        - name: 'emea.esslingen'
          url: 'https://ftp-stud.hs-esslingen.de/Mirrors/archive.parrotsec.org'
          index: index.db.iso
        - name: 'emea.nluug'
          url: 'https://ftp.nluug.nl/os/Linux/distr/parrot'
          index: index.db.iso
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db.iso
  EU:
    DEFAULT:
      mirrors:
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db.iso
        - name: 'emea.esslingen'
          url: 'https://ftp-stud.hs-esslingen.de/Mirrors/archive.parrotsec.org'
          index: index.db.iso
        - name: 'emea.nluug'
          url: 'https://ftp.nluug.nl/os/Linux/distr/parrot'
          index: index.db.iso
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db.iso
    IT:
      mirrors:
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db.iso
    DE:
      mirrors:
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db.iso
        - name: 'emea.esslingen'
          url: 'https://ftp-stud.hs-esslingen.de/Mirrors/archive.parrotsec.org'
          index: index.db.iso
        - name: emea.pyratelan
          url: https://mirror.pyratelan.org/parrot
          index: index.db.iso
    NL:
      mirrors:
        - name: 'emea.nluug'
          url: 'https://ftp.nluug.nl/os/Linux/distr/parrot'
          index: index.db.iso
        - name: emea.lyrahosting
          url: https://mirror.lyrahosting.com/parrot
          index: index.db.iso
        #- name: 'emea.wasabi-amsterdam'
        #  url: 'https://s3.eu-central-1.wasabisys.com/parrot-amsterdam'
        #  index: index.db.iso
    SE:
      mirrors:
        - name: 'emea.umu'
          url: 'https://ftp.acc.umu.se/mirror/parrotsec.org/parrot'
          index: index.db.iso
    GR:
      mirrors:
        - name: 'emea.uoc'
          url: 'https://ftp.cc.uoc.gr/mirrors/linux/parrot'
          index: index.db.iso
    BE:
      mirrors:
        - name: 'emea.belnet'
          url: 'https://ftp.belnet.be/pub/archive.parrotsec.org'
          index: index.db.iso
    ES:
      mirrors:
        - name: 'emea.osluz'
          url: 'https://matojo.unizar.es/parrot'
          index: index.db.iso
    PT:
      mirrors:
        - name: 'emea.up'
          url: 'https://mirrors.up.pt/parrot'
          index: index.db.iso
    DK:
      mirrors:
        - name: 'emea.dotsrc'
          url: 'https://mirrors.dotsrc.org/parrot'
          index: index.db.iso
    FR:
      mirrors:
        - name: 'emea.cythin'
          url: 'https://parrot.mirror.cythin.com/parrot'
          index: index.db.iso
        - name: emea.iriseden
          url: https://parrot-mirror.iriseden.eu
          index: index.db.iso
    HU:
      mirrors:
        - name: 'emea.quantum'
          url: 'https://quantum-mirror.hu/mirrors/pub/parrot'
          index: index.db.iso
    EE:
      mirrors:
        - name: emea.cspacehosting
          url: https://mirror.cspacehostings.com/parrotsec
          index: index.db.iso
    UA:
      mirrors:
        - name: emea.astra
          url: https://parrot.astra.in.ua/
          index: index.db.iso
    RU:
      mirrors:
        - name: 'apac.yandex'
          url: 'https://mirror.yandex.ru/mirrors/parrot'
          index: index.db.iso
          blocked_countries: [ 'UA' ]
        - name: apac.surf
          url: https://mirror.surf/parrot
          index: index.db.iso
  AF:
    DEFAULT:
      mirrors:
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db.iso
        - name: 'emea.esslingen'
          url: 'https://ftp-stud.hs-esslingen.de/Mirrors/archive.parrotsec.org'
          index: index.db.iso
        - name: 'emea.nluug'
          url: 'https://ftp.nluug.nl/os/Linux/distr/parrot'
          index: index.db.iso
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db.iso
  NA:
    #DEFAULT:
      #mirrors:
        #- name: 'ncsa.wasabi-virginia'
        #  url: 'https://s3.us-east-2.wasabisys.com/parrot-virginia'
        #  index: index.db.iso
        #- name: 'ncsa.wasabi-oregon'
        #  url: 'https://s3.us-west-1.wasabisys.com/parrot-oregon'
        #  index: index.db.iso
        #- name: 'ncsa.wasabi-texas'
        #  url: 'https://s3.us-central-1.wasabisys.com/parrot-texas'
        #  index: index.db.iso
        #- name: emea.linode-newyork
        #  url: https://parrot.us-east-1.linodeobjects.com/parrot
        #  index: index.db.iso
    CA:
      mirrors:
        - name: ncsa.0xem
          url: https://mirror.0xem.ma/parrot/
          index: index.db.iso
    US:
      mirrors:
        - name: 'ncsa.mit'
          url: 'https://mirrors.mit.edu/parrot'
          index: index.db.iso
        - name: 'ncsa.clarkson'
          url: 'https://mirror.clarkson.edu/parrot'
          index: index.db.iso
        - name: 'ncsa.osuosl'
          url: 'https://ftp.osuosl.org/pub/parrotos'
          index: index.db.iso
        - name: 'ncsa.berkeley'
          url: 'https://mirrors.ocf.berkeley.edu/parrot'
          index: index.db.iso
  SA:
    DEFAULT:
      mirrors:
        - name: 'ncsa.cedia'
          url: 'https://mirror.cedia.org.ec/parrot'
          index: index.db.iso
        - name: 'ncas.uta'
          url: 'https://mirror.uta.edu.ec/parrot'
          index: index.db.iso
        - name: 'ncsa.ueb'
          url: 'https://mirror.ueb.edu.ec/parrot'
          index: index.db.iso
        - name: 'ncsa.usp'
          url: 'http://sft.if.usp.br/parrot'
          index: index.db.iso
    EC:
      mirrors:
        - name: 'ncsa.cedia'
          url: 'https://mirror.cedia.org.ec/parrot'
          index: index.db.iso
        - name: 'ncas.uta'
          url: 'https://mirror.uta.edu.ec/parrot'
          index: index.db.iso
        - name: 'ncsa.ueb'
          url: 'https://mirror.ueb.edu.ec/parrot'
          index: index.db.iso
    BR:
      mirrors:
        - name: 'ncsa.usp'
          url: 'http://sft.if.usp.br/parrot'
          index: index.db.iso
  AS:
    DEFAULT:
      mirrors:
        - name: 'apac.0x'
          url: 'https://mirror.0x.sg/parrot'
          index: index.db.iso
        - name: 'apac.nchc'
          url: 'https://free.nchc.org.tw/parrot'
          index: index.db.iso
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db.iso
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db.iso
    IN:
      mirrors:
        - name: 'apac.0x'
          url: 'https://mirror.0x.sg/parrot'
          index: index.db.iso
        - name: 'apac.nchc'
          url: 'https://free.nchc.org.tw/parrot'
          index: index.db.iso
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db.iso
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db.iso
    IR:
      mirrors:
      - name: 'apac.mobinhost'
        url: 'https://mirrors.mobinhost.com/parrot/'
        index: index.db.iso
    TW:
      mirrors:
        - name: 'apac.nchc'
          url: 'https://free.nchc.org.tw/parrot'
          index: index.db.iso
    SG:
      mirrors:
        - name: 'apac.0x'
          url: 'https://mirror.0x.sg/parrot'
          index: index.db.iso
    KR:
      mirrors:
        - name: apac.krmir
          url: https://mirror.krmir.org/parrot
          index: index.db.iso
    CN:
      mirrors:
        - name: 'apac.ustc'
          url: 'https://mirrors.ustc.edu.cn/parrot'
          index: index.db.iso
        - name: 'apac.sjtug'
          url: 'https://mirrors.sjtug.sjtu.edu.cn/parrot'
          index: index.db.iso
        - name: 'apac.tuna'
          url: 'https://mirrors.tuna.tsinghua.edu.cn/parrot'
          index: index.db.iso
    TH:
      mirrors:
        - name: 'apac.kku'
          url: 'https://mirror.kku.ac.th/parrot'
          index: index.db.iso
        - name: 'apac.nipacloud'
          url: 'https://mirrors.nipa.cloud/parrot'
          index: index.db.iso
  OC:
    DEFAULT:
      mirrors:
        - name: 'apac.0x'
          url: 'https://mirror.0x.sg/parrot'
          index: index.db.iso
        - name: 'apac.nchc'
          url: 'https://free.nchc.org.tw/parrot'
          index: index.db.iso
    NZ:
      mirrors:
        - name: 'apac.takeshi'
          url: 'https://mirrors.takeshi.nz/parrot'
          index: index.db.iso
    NC:
      mirrors:
        - name: 'apac.lagoon'
          url: 'https://mirror.lagoon.nc/pub/parrot'
          index: index.db.iso
