continents:
  MASTER:
    MASTER:
      mirrors:
        - name: "Master"
          url: "https://deb.parrot.sh/mirrors/parrot"
          index: index.db
          version: 9999
          down: false
  DEFAULT:
    DEFAULT:
      mirrors:
        - name: 'cdn.bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: index.db
        - name: 'ncsa.wasabi-virginia'
          url: 'https://s3.us-east-2.wasabisys.com/parrot-virginia'
          index: index.db
        - name: 'ncsa.wasabi-oregon'
          url: 'https://s3.us-west-1.wasabisys.com/parrot-oregon'
          index: index.db
        - name: 'ncsa.wasabi-texas'
          url: 'https://s3.us-central-1.wasabisys.com/parrot-texas'
          index: index.db
        - name: 'ncsa.wasabi-tokyo'
          url: 'https://s3.ap-northeast-1.wasabisys.com/parrot-tokyo'
          index: index.db
        - name: 'ncsa.wasabi-amsterdam'
          url: 'https://s3.eu-central-1.wasabisys.com/parrot-virginia'
          index: index.db
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db
        - name: 'emea.esslingen'
          url: 'https://ftp-stud.hs-esslingen.de/Mirrors/archive.parrotsec.org'
          index: index.db
        - name: 'emea.nluug'
          url: 'https://ftp.nluug.nl/os/Linux/distr/parrot'
          index: index.db
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db
  EU:
    DEFAULT:
      mirrors:
        - name: 'emea.wasabi-amsterdam'
          url: 'https://s3.eu-central-1.wasabisys.com/parrot-amsterdam'
          index: index.db
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db
        - name: 'emea.esslingen'
          url: 'https://ftp-stud.hs-esslingen.de/Mirrors/archive.parrotsec.org'
          index: index.db
        - name: 'emea.nluug'
          url: 'https://ftp.nluug.nl/os/Linux/distr/parrot'
          index: index.db
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db
    # disabled: redirector not ready for iso-only mirrors
    #    - name: emea.linode-frankfurt
    #      url: https://parrot.eu-central-1.linodeobjects.com/parrot
    #      index: index.db.iso
    IT:
      mirrors:
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db
    DE:
      mirrors:
        - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db
        - name: 'emea.esslingen'
          url: 'https://ftp-stud.hs-esslingen.de/Mirrors/archive.parrotsec.org'
          index: index.db
        - name: emea.pyratelan
          url: https://mirror.pyratelan.org/parrot
          index: index.db
    NL:
      mirrors:
        - name: 'emea.nluug'
          url: 'https://ftp.nluug.nl/os/Linux/distr/parrot'
          index: index.db
        - name: emea.lyrahosting
          url: https://mirror.lyrahosting.com/parrot
          index: index.db
        - name: 'emea.wasabi-amsterdam'
          url: 'https://s3.eu-central-1.wasabisys.com/parrot-amsterdam'
          index: index.db
    SE:
      mirrors:
        - name: 'emea.umu'
          url: 'https://ftp.acc.umu.se/mirror/parrotsec.org/parrot'
          index: index.db
    GR:
      mirrors:
        - name: 'emea.uoc'
          url: 'https://ftp.cc.uoc.gr/mirrors/linux/parrot'
          index: index.db
    BE:
      mirrors:
        - name: 'emea.belnet'
          url: 'https://ftp.belnet.be/pub/archive.parrotsec.org'
          index: index.db
    ES:
      mirrors:
        - name: 'emea.osluz'
          url: 'https://matojo.unizar.es/parrot'
          index: index.db
    PT:
      mirrors:
        - name: 'emea.up'
          url: 'https://mirrors.up.pt/parrot'
          index: index.db
    DK:
      mirrors:
        - name: 'emea.dotsrc'
          url: 'https://mirrors.dotsrc.org/parrot'
          index: index.db
    FR:
      mirrors:
        - name: 'emea.cythin'
          url: 'https://parrot.mirror.cythin.com/parrot'
          index: index.db
        - name: emea.iriseden
          url: https://parrot-mirror.iriseden.eu
          index: index.db
    HU:
      mirrors:
        - name: 'emea.quantum'
          url: 'https://quantum-mirror.hu/mirrors/pub/parrot'
          index: index.db
    EE:
      mirrors:
        - name: emea.cspacehosting
          url: https://mirror.cspacehostings.com/parrotsec
          index: index.db
    RU:
      mirrors:
        - name: 'apac.yandex'
          url: 'https://mirror.yandex.ru/mirrors/parrot'
          index: index.db
          blocked_countries: [ 'UA' ]
        - name: apac.surf
          url: https://mirror.surf/parrot
          index: index.db
    # disabled: no https support
    #    - name: 'apac.truenetwork'
    #      url: 'http://mirror.truenetwork.ru/parrot'
    #      index: index.db
    # disabled: redirector not ready for iso-only mirrors
    #           and no https support
    #UA:
    #  mirrors:
    #    - name: 'emea.comsys'
    #      url: 'http://mirrors.comsys.kpi.ua/parrot'
    #      index: index.db.iso
  AF:
    DEFAULT:
      mirrors:
         - name: 'emea.halifax'
          url: 'https://ftp.halifax.rwth-aachen.de/parrotsec'
          index: index.db
        - name: 'emea.esslingen'
          url: 'https://ftp-stud.hs-esslingen.de/Mirrors/archive.parrotsec.org'
          index: index.db
        - name: 'emea.nluug'
          url: 'https://ftp.nluug.nl/os/Linux/distr/parrot'
          index: index.db
        - name: 'emea.garr'
          url: 'https://parrot.mirror.garr.it/parrot'
          index: index.db
  NA:
    # disabled: redirector not ready for iso-only mirrors
    #    - name: emea.linode-newyork
    #      url: https://parrot.us-east-1.linodeobjects.com/parrot
    #      index: index.db.iso
    CA:
      mirrors:
        - name: ncsa.0xem
          url: https://mirror.0xem.ma/parrot/
          index: index.db
        - name: 'ncsa.wasabi-virginia'
          url: 'https://s3.us-east-2.wasabisys.com/parrot-virginia'
          index: index.db
    US:
      mirrors:
        - name: 'ncsa.wasabi-virginia'
          url: 'https://s3.us-east-2.wasabisys.com/parrot-virginia'
          index: index.db
        - name: 'ncsa.wasabi-oregon'
          url: 'https://s3.us-west-1.wasabisys.com/parrot-oregon'
          index: index.db
        - name: 'ncsa.wasabi-texas'
          url: 'https://s3.us-central-1.wasabisys.com/parrot-texas'
          index: index.db
        - name: 'ncsa.mit'
          url: 'https://mirrors.mit.edu/parrot'
          index: index.db
        - name: 'ncsa.clarkson'
          url: 'https://mirror.clarkson.edu/parrot'
          index: index.db
        - name: 'ncsa.osuosl'
          url: 'https://ftp.osuosl.org/pub/parrotos'
          index: index.db
        - name: 'ncsa.berkeley'
          url: 'https://mirrors.ocf.berkeley.edu/parrot'
          index: index.db
  SA:
    DEFAULT:
      mirrors:
        - name: 'cdn.bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: index.db
    EC:
      mirrors:
        - name: 'ncsa.cedia'
          url: 'https://mirror.cedia.org.ec/parrot'
          index: index.db
        - name: 'ncas.uta'
          url: 'https://mirror.uta.edu.ec/parrot'
          index: index.db
        - name: 'ncsa.ueb'
          url: 'https://mirror.ueb.edu.ec/parrot'
          index: index.db
    BR:
      mirrors:
        - name: 'ncsa.usp'
          url: 'http://sft.if.usp.br/parrot'
          index: index.db
  AS:
    DEFAULT:
      mirrors:
        - name: 'cdn.bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: index.db
    # disabled: redirector not ready for iso-only mirrors
    #    - name: emea.linode-singapore
    #      url: https://parrot.ap-south-1.linodeobjects.com/parrot
    #      index: index.db.iso
    # disabled: no https support
    #BD:
    #  mirrors:
    #    - name: 'apac.amberit'
    #      url: 'http://mirror.amberit.com.bd/parrotsec'
    #      index: index.db
    IN:
      mirrors:
        - name: 'ncsa.wasabi-tokyo'
          url: 'https://s3.ap-northeast-1.wasabisys.com/parrot-tokyo'
          index: index.db
        - name: 'apac.0x'
          url: 'https://mirror.0x.sg/parrot'
          index: index.db
        - name: 'emea.wasabi-amsterdam'
          url: 'https://s3.eu-central-1.wasabisys.com/parrot-amsterdam'
          index: index.db;
    TW:
      mirrors:
        - name: 'apac.nchc'
          url: 'https://free.nchc.org.tw/parrot'
          index: index.db
    SG:
      mirrors:
        - name: 'apac.0x'
          url: 'https://mirror.0x.sg/parrot'
          index: index.db
    JP:
      mirrors:
        - name: 'ncsa.wasabi-tokyo'
          url: 'https://s3.ap-northeast-1.wasabisys.com/parrot-tokyo'
          index: index.db
    KR:
      mirrors:
        - name: apac.krmir
          url: https://mirror.krmir.org/parrot
          index: index.db
    CN:
      mirrors:
        - name: 'apac.ustc'
          url: 'https://mirrors.ustc.edu.cn/parrot'
          index: index.db
  # disabled: no https support
  #      - name: 'apac.shu'
  #        url: 'http://mirrors.shu.edu.cn/parrot'
  #        index: index.db
        - name: 'apac.sjtug'
          url: 'https://mirrors.sjtug.sjtu.edu.cn/parrot'
          index: index.db
        - name: 'apac.tuna'
          url: 'https://mirrors.tuna.tsinghua.edu.cn/parrot'
          index: index.db
    TH:
      mirrors:
        - name: 'apac.kku'
          url: 'https://mirror.kku.ac.th/parrot'
          index: index.db
    # disabled: no https support
    #ID:
    #  mirrors:
    #    - name: 'apac.datautama'
    #      url: 'http://kartolo.sby.datautama.net.id/parrot'
    #      index: index.db
  OC:
    DEFAULT:
      mirrors:
        - name: 'cdn.bunny'
          url: 'https://bunny.deb.parrot.sh/parrot'
          index: index.db
        - name: 'ncsa.wasabi-tokyo'
          url: 'https://s3.ap-northeast-1.wasabisys.com/parrot-tokyo'
          index: index.db
        - name: 'apac.0x'
          url: 'https://mirror.0x.sg/parrot'
          index: index.db
    # disabled: redirector not ready for iso-only mirrors
    #    - name: emea.linode-singapore
    #      url: https://parrot.ap-south-1.linodeobjects.com/parrot
    #      index: index.db.iso
    NZ:
      mirrors:
        - name: 'apac.takeshi'
          url: 'https://mirrors.takeshi.nz/parrot'
          index: index.db
    NC:
      mirrors:
        - name: 'apac.lagoon'
          url: 'https://mirror.lagoon.nc/pub/parrot'
          index: index.db
